// Auth Action Types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// Home Action Types (for lookups and data)
export const FETCH_LOOKUP_VALUES = 'FETCH_LOOKUP_VALUES';
export const CATEGORIES = 'CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING';
export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR';
export const FETCH_TRENDING_PRODUCTS = 'FETCH_TRENDING_PRODUCTS';
export const FETCH_LATEST_PRODUCTS = 'FETCH_LATEST_PRODUCTS';
export const FETCH_RECOMMENDED_PRODUCTS = 'FETCH_RECOMMENDED_PRODUCTS';
export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const SET_PRODUCT_DETAIL_LOADING = 'SET_PRODUCT_DETAIL_LOADING';